connectedin/urls.py
from django.contrib import admin
from django.urls import path
from perfil import views as views_perfil
from usuario.views import RegistrarUsuarioView
from django.contrib.auth import views as views_user
from timeline import views as views_timeline

urlpatterns = [
    # Perfil.views
    path('admin/', admin.site.urls),
    path('', views_perfil.index, name='index'),
    path('perfil/<int:perfil_id>',
    				views_perfil.exibir, name='exibir'),
    path('perfil/<int:perfil_id>/convidar',
    				views_perfil.convidar, name='convidar'),
    path('perfil/<int:convite_id>/aceitar',
                    views_perfil.aceitar, name='aceitar'),
    path('perfil/<int:convite_id>/rejeitar',
                    views_perfil.rejeitar, name='rejeitar'),

    # Usuario.views
    path('registrar/', RegistrarUsuarioView.as_view(),
                    name='registrar'),
    path('login/', views_user.LoginView.as_view(template_name='usuario/login.html'),
                    name='login'),
    path('logout/', views_user.LogoutView.as_view(template_name='usuario/login.html'),
                    name='logout'),

    # Timeline.views
    path('timeline/add_post', views_timeline.add_post, name='add_post'),
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import User
from timeline.models import *

class Perfil(models.Model):
	nome = models.CharField(max_length=255, null=False)
	telefone = models.CharField(max_length=15, null=False)
	nome_empresa = models.CharField(max_length=80, null=False)
	sobre = models.CharField(max_length=255, null=False)
	contatos = models.ManyToManyField('self')
	usuario = models.OneToOneField(User,
		related_name='perfil', on_delete = models.CASCADE)

	@property
	def email(self):
		return self.usuario.email

	def convidar(self, perfil_convidado):
		convite = Convite(solicitados=self,
							recebidos=perfil_convidado)
		convite.save()

class Convite(models.Model):
	solicitados = models.ForeignKey(Perfil,
		related_name = 'convites_feitos',
		on_delete = models.CASCADE)
	recebidos = models.ForeignKey(Perfil, 
		related_name = 'convites_recebidos',
		on_delete = models.CASCADE)

	def aceitar(self):
		self.recebidos.contatos.add(self.solicitados)
		self.solicitados.contatos.add(self.recebidos)
		self.delete()

	def rejeitar(self):
		self.delete()

timeline/models.py
from django.db import models

class Postagem(models.Model):
	texto = models.TextField()
	data_hora = models.DateTimeField(auto_now_add=True)
	perfil = models.ForeignKey('perfil.Perfil',
		related_name = 'postagem',
		on_delete = models.CASCADE)

	class Meta:
		ordering = ['-data_hora']

	def __str__(self):
		return self.texto

usuario/models.py
from django.db import models

# Create your models here.

timeline/forms.py
from django.forms import ModelForm
from timeline.models import *

class PostagemForm(ModelForm):
	class Meta:
		model = Postagem
		fields = ['texto']

usuario/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
	nome = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	senha = forms.CharField(required=True)
	telefone = forms.CharField(required=True)
	nome_empresa = forms.CharField(required=True)
	sobre = forms.CharField(required=True)

	def is_valid(self):
		valid = True
		if not super(RegistrarUsuarioForm, self).is_valid():
			self.adiciona_erro('Por favor, verifique os dados informados')
			valid = False

		user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
		if user_exists:
			self.adiciona_erro('Usuário já cadastrado!')
			valid = False

		return valid

	def adiciona_erro(self, message):
		errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,
										 forms.utils.ErrorList())
		errors.append(message)

perfil/views.py
from django.shortcuts import render
from perfil.models import Perfil, Convite
from django.shortcuts import redirect
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.contrib.auth.decorators import login_required
from timeline.models import *
from timeline.forms import *

@login_required
def index(request):
	perfil = Perfil.objects.all()
	perfil_logado = get_perfil_logado(request)

	my_contatos = perfil_logado.contatos.all()
	all_posts = Postagem.objects.all()
	postagem = []
	for post in all_posts:
		if post.perfil in my_contatos or post.perfil == perfil_logado:
			postagem.append(post)

	paginator = Paginator(postagem,3)
	
	try:
		page = int(request.GET.get('page','1'))
	except:
		page = 1

	try:
		postagem = paginator.page(page)
	except:
		postagem = paginator.page(paginator.num_pages)

	return render(request, 'perfil/index.html',
				{'perfil' : perfil,
				'postagem' : postagem,
				'perfil_logado' : perfil_logado})

@login_required
def exibir(request, perfil_id):
	perfil = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	eh_contato = perfil in perfil_logado.contatos.all()
	return render(request, 'perfil/perfil.html',
				{'perfil' : perfil,
				'perfil_logado' : perfil_logado,
				'eh_contato' : eh_contato})

@login_required
def convidar(request, perfil_id):
	perfil_convidado = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	perfil_logado.convidar(perfil_convidado)
	return redirect('index')

@login_required
def aceitar(request, convite_id):
	convite = Convite.objects.get(id=convite_id)
	convite.aceitar()
	return redirect('index')

@login_required
def rejeitar(request, convite_id):
	convite = Convite.objects.get(id=convite_id)
	convite.rejeitar()
	return redirect('index')

@login_required
def get_perfil_logado(request):
	return request.user.perfil

timeline/views.py
from django.shortcuts import render
from perfil.models import *
from django.shortcuts import redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from timeline.models import *
from timeline.forms import *

@login_required
def add_post(request):
	if request.method == 'POST':
		form = PostagemForm(request.POST)
		if form.is_valid():
			model_instance = form.save(commit=False)
			model_instance.perfil = get_perfil_logado(request)
			model_instance.save()
			return redirect('index')
	else:
		form = PostagemForm()
		return render(request, "timeline/add_post.html", {'form': form})

@login_required
def get_perfil_logado(request):
	return request.user.perfil

usuario/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfil.models import Perfil
from usuario.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
	template_name = 'usuario/registrar.html'

	def get(self, request):
		return render(request, self.template_name)

	def post(self, request):
		form = RegistrarUsuarioForm(request.POST)
		if form.is_valid():
			dados_form = form.cleaned_data
			usuario = User.objects.create_user(username = dados_form['nome'],
			email = dados_form['email'],
			password = dados_form ['senha'])

			perfil = Perfil(nome=dados_form['nome'],
			telefone=dados_form['telefone'],
			nome_empresa=dados_form['nome_empresa'],
			sobre=dados_form['sobre'],
			usuario=usuario)

			perfil.save()
			return redirect('index')
		
		return render(request, self.template_name, {'form' : form})

perfil/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>ConnectedIn</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'/>
	<script src='http://code.jquery.com/jquery-2.1.3.min.js'></script>
	<script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{%url 'index' %}" style="text-decoration: none;">
			ConnectedIn
		</a>
		<div class="collapse navbar-collapse" id="navbarNavDropdown" style="position: absolute; right: 10px">
			<ul class="navbar-nav">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Solicitações recebidas
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="overflow: auto; width: 170px; height: 200px; border:solid 1px">
					{% with total_convites=perfil_logado.convites_recebidos.count %}
						
						<div class="panel-heading">
							<strong>
							Você tem
							{{ perfil_logado.convites_recebidos.count }}
							convite{{ perfil_logado.convites_recebidos.count|pluralize }}
							aguardando aprovação
							</strong>
						</div>

						{% if total_convites %}
						<ul class="list-group">
							{% for convite in perfil_logado.convites_recebidos.all %}
								<li class="dropdown-item">
									{{convite.solicitados.nome}}
									<a href="{% url 'aceitar' convite.id%}" class="pull-right">aceitar</a>
								</li>
							{% endfor %}
						</ul>
						{% endif %}

					{% endwith %}
					</div>

				</li>
				<li class="nav-item active">
					<a class="nav-link" href="#">Logout <span class="sr-only">(current)</span></a>
				</li>
			</ul>

		</div>
	</nav>

	<div class="container">
		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>
	</div>

</body>
</html>

perfil/templates/index.html
{% extends "base.html" %}
{% block body %}
	
	<div class="col-pg-12">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Todos os perfis</h1>
			</div>
			
			{% if perfil %}
				<ul>
					{% for profile in perfil %}
						{% if profile.nome != perfil_logado.nome %}
							<li>
								<a href="{% url 'exibir' profile.id %}">{{profile.nome}}
								</a> / {{profile.email}}
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			{% else %}
				<p>Nenhum perfil encontrado</p>
			{% endif %}

		<br>

			<div class="container">
				<span>
					Página {{perfil.number}} de {{perfil.paginator.num_pages}}
				</span>

				{% if perfil.has_next %}
					<a href="?page={{perfil.next_page_number}}">próximo</a>
				{% endif %}

				{% if perfil.has_previous %}
					<a href="?page={{perfil.previous_page_number}}">anterior</a>
				{% endif %}
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		{% with total_de_contatos=perfil_logado.contatos.count %}
			{% if total_de_contatos %}
				<div class="panel-heading">
					<strong>Você tem {{total_de_contatos}}
					contato{{ total_de_contatos|pluralize }}</strong>
				</div>

				{% for contato in perfil_logado.contatos.all %}
				<ul>
					<li>
						<a href="{% url 'exibir' contato.id %}">{{contato.nome}}
						</a> / {{contato.email}}
					</li>
				</ul>
				{% endfor %}

			{% else %}
				<div class="panel-body">
					<p>Você não possui contatos no momento :(</p>
				</div>
			{% endif %}
		{% endwith %}
	</div>

{% endblock %}
</body>
</html>

perfil/templates/perfil.html
{% extends "base.html" %}
{% block body %}

	<div class="row">
		<div class="col-lg-12">
			<h2>{{perfil.nome}}</h2>
			<ul style="list-style: georgian outside url('/non-existent.svg');">
				<li>{{perfil.nome_empresa}}</li>
				<li><a href="mailto:{{perfil.email}}">{{perfil.email}}</a></li>
				<li>{{perfil.telefone}}</li>
				<li>Sobre: {{perfil.sobre}}</li>
			</ul>
			
			{% if eh_contato %}
				<div class="well well-sm">Vocês estão conectados!</div>
			{% else %}
				<a href="{% url 'convidar' perfil.id %}">Convidar</a>
			{% endif %}

		</div>
	</div>

{% endblock %}
</body>
</html>

perfil/templates/perfil/base.html
<!DOCTYPE html>
<html>
<head>
	<title>ConnectedIn</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="../static/styles/main.css">
	<link rel="stylesheet" type="text/css" href="../static/styles/signin.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'/>
	<script src='http://code.jquery.com/jquery-2.1.3.min.js'></script>
	<script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		
		<a class="navbar-brand" href="{%url 'index' %}">
			ConnectedIn
		</a>

		{% block logado %}
		<div class="collapse navbar-collapse navbar-right" id="navbarNavDropdown">
			
			<ul class="navbar-nav">
				
				<li class="nav-item dropdown">
					
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Solicitações recebidas
					</a>
					
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					
					{% with total_convites=perfil_logado.convites_recebidos.count %}
						
						<div class="panel-heading">
							<strong>
							Você tem
							{{ perfil_logado.convites_recebidos.count }}
							convite{{ perfil_logado.convites_recebidos.count|pluralize }}
							aguardando aprovação
							</strong>
						</div>

						{% if total_convites %}
						<ul class="list-group">
							
							{% for convite in perfil_logado.convites_recebidos.all %}
								<li class="dropdown-item">
									{{convite.solicitados.nome}}
									<a href="{% url 'aceitar' convite.id%}" class="convite">aceitar</a>
									<a href="{% url 'rejeitar' convite.id %}" class="convite convite_reject">rejeitar</a>
								</li>
							
							{% endfor %}

						</ul>
						{% endif %}

					{% endwith %}

					</div>
				</li>
				
				<li class="nav-item">
			    	<a class="nav-link" href="/logout/">Logout</a>
			    </li>

			</ul>

		</div>
		{% endblock %}

	</nav>

	<div class="container">

		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>

	</div>

</body>
</html>

perfil/templates/perfil/index.html
{% extends "perfil/base.html" %}
{% block body %}
	
	<div class="container">

		<div class="card mb-3">

			<div class="card-header text-center">
				<h2>Welcome, {{perfil_logado.nome}}</h2>
			</div>

			<ul class="nav nav-tabs justify-content-center nav-fill" id="myTab" role="tablist">
			  	<li class="nav-item">
			    	<a class="nav-link" id="timeline-tab" data-toggle="tab" href="#timeline" role="tab" aria-controls="timeline" aria-selected="true">Timeline</a>
			  	</li>
			  	<li class="nav-item">
			    	<a class="nav-link" id="profiles-tab" data-toggle="tab" href="#profiles" role="tab" aria-controls="profiles" aria-selected="false">Profiles</a>
			  	</li>
			  	<li class="nav-item">
			    	<a class="nav-link" id="contacts-tab" data-toggle="tab" href="#contacts" role="tab" aria-controls="contacts" aria-selected="false">Contacts</a>
			  	</li>
			</ul>

			<!-- Tab panes -->
			<div class="tab-content">

			  	<div class="tab-pane" id="timeline" role="tabpanel" aria-labelledby="timeline-tab">
			  		<br>
			  		<div class="text-right">
						<a href="{% url 'add_post' %}">Add publication (+)</a>
					</div>
					<br>

					{% if postagem %}
						
						{% for post in postagem %}
							<div class="card border-dark mb-3">
								<div class="card-header">{{post.perfil.nome}}</div>
								<div class="card-body">
								    <p class="card-text">{{post.texto}}</p>
								    <!-- <p class="card-text">Reactions</p> -->
								    <!-- <a href="#" class="card-link">Comment</a> -->
								    <p class="card-text"><small class="text-muted">Post in {{post.data_hora}}</small></p>
								</div>
							</div>
						{% endfor %}

						<div class="card-body text-center">
							{% if postagem.has_previous %}
							<button>
								<a class="card-link" href="?page={{postagem.previous_page_number}}">Previous posts</a>
							</button>
							{% endif %}

							{% if postagem.has_next %}
							<button>
								<a class="card-link" href="?page={{postagem.next_page_number}}">Next posts</a>
							</button>
							{% else %}
								<p class="nav-link">END<a class="nav-link" href="{% url 'index' %}">Back to start</a></p>
							{% endif %}
						</div>

					{% else %}
						<div class="container text-center">
							<p>No posts to show</a>
						</div>
					{% endif %}

			  	</div>

			  	<div class="tab-pane" id="profiles" role="tabpanel" aria-labelledby="profiles-tab">
			  		{% if perfil %}
						<ul><h4>All profiles:</h4> 

							{% for profile in perfil %}
								
								{% if profile.nome != perfil_logado.nome %}
									<li>
										<a href="{% url 'exibir' profile.id %}">{{profile.nome}}
										</a> / {{profile.email}}
									</li>
								{% endif %}

							{% endfor %}

						</ul>
					{% else %}
						<p>Nenhum perfil encontrado</p>
					{% endif %}

			  	</div>

			  	<div class="tab-pane" id="contacts" role="tabpanel" aria-labelledby="contacts-tab">
			  		<div class="card-body">
						{% with total_de_contatos=perfil_logado.contatos.count %}
							
							{% if total_de_contatos %}
								<div class="panel-heading">
									<strong>Você tem {{total_de_contatos}}
									contato{{ total_de_contatos|pluralize }}</strong>
								</div>

								{% for contato in perfil_logado.contatos.all %}
								<ul class="card-body">
									<a href="{% url 'exibir' contato.id %}">{{contato.nome}}
									</a> / {{contato.email}}
								</ul>
								{% endfor %}

							{% else %}

								<div class="panel-heading">
									<strong>Você não possui contatos :(</strong>
								</div>

							{% endif %}

						{% endwith %}

					</div>
			  	</div>

			</div>

			<script>
				$('#myTab li:first-child a').tab('show');
			</script>

		</div>

	</div>

{% endblock %}

perfil/templates/perfil/perfil.html
{% extends "perfil/base.html" %}
{% block body %}

	<div class="row">
		<div class="col-lg-12">
			<h2>{{perfil.nome}}</h2>
			<ul class="list-perfil">
				<li>{{perfil.nome_empresa}}</li>
				<li><a href="mailto:{{perfil.email}}">{{perfil.email}}</a></li>
				<li>{{perfil.telefone}}</li>
				<li>Sobre: {{perfil.sobre}}</li>
			</ul>
			
			{% if eh_contato %}
				<div class="well well-sm">Vocês estão conectados!</div>
			{% else %}
				<a href="{% url 'convidar' perfil.id %}">Convidar</a>
			{% endif %}

		</div>
	</div>

{% endblock %}

timeline/templates/timeline/add_post.html
{% extends "perfil/base.html" %}

{% block body %}

<form class="form-signin" enctype="multipart/form-data" action="{% url 'add_post' %}" method="POST">
	{% csrf_token %}
	<h3 class="form-signin-heading">New Post:</h3>

	<br>

	<div class="form-group">
	    <label for="texto">Escreva algo: </label>
	    <textarea class="form-control" id="id_texto" placeholder="Digite aqui" rows="8" cols="40" name="texto" required></textarea>
	</div>

	<button class="btn btn-primary" type="submit" value="Add">Postar</button>

</form>

{% endblock %}

usuario/templates/usuario/login.html
{% extends "perfil/base.html" %}

{% block logado %}
{% endblock %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'login' %}" method="post">
	{% csrf_token %}

	<h2 class="form-signin-heading">Login</h2>
	<input id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>
	<input type="password" id="id_password" class="form-control" name="password" placeholder="Senha" required>
	<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
	
	{% if form.errors %}
		<div class="alert alert-danger">
			<button type="button" class="close"
			data-dismiss="alert" aria-hidden="true">×</button>
			Por favor, verifique o Email e/ou Senha informados
		</div>
	{% endif %}
	
	<a href="{% url 'registrar' %}">Realizar cadastro</a>

</form>

{% endblock %}

usuario/templates/usuario/registrar.html
{% extends "perfil/base.html" %}

{% block logado %}
{% endblock %}

{% block body %}

<form class="form-signin" action="{% url 'registrar' %}" method="POST">
	{% csrf_token %}
	<h2 class="form-signin-heading">Crie seu usuário:</h2>
	<input id="id_nome" name="nome" class="form-control" placeholder="Nome" required autofocus="">	
	<input id="id_email" name="email" class="form-control" placeholder="Email" required>	
	<input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha" required>
	
	<br>

	<input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required>
	<input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required>
	<textarea id='id_sobre' name="sobre" class="form-control" placeholder="Sobre" rows="8" cols="70" required></textarea>

	<br>

	<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

	{% if form.errors %}
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert" 
		aria-hidden="true"></button>
		{{form.non_field_errors}}
	</div>
	{% endif %}

</form>

{% endblock %}